# /app-management/configuration/vnpt/global
title: Global Settings
apiEndpoint: /api/consul/config
queryParams:
  key: config/spoofing/data
fields:
  - key: application
    type: tabset
    className: mb-3
    templateOptions:
      type: pills
    fieldGroup:
      - templateOptions:
          label: General Settings
        className: card-body
        fieldGroupClassName: card my-3
        fieldGroup:
          - key: mcc
            type: input
            className: col-md-6
            defaultValue: '84'
            templateOptions:
              label: Mobile Country Code
              description: Automatically convert non-E164 MSISDN into E164 format using this country code. Leave blank to bypass phone number conversion
          - key: gtprefix
            type: input
            className: col-md-6
            defaultValue: '84'
            templateOptions:
              label: GT Prefix
              description: GT Prefix of network nodes to check against. If subscriber is located under this GT prefix, the call is pass into OK destination, else FORBIDDEN destination.
          - key: hlr-prefix
            type: tags
            className: col-md-6
            defaultValue: ['84']
            templateOptions:
              label: HLR Prefixes
              description: Allowed GT Prefixes to continue processing
          - key: timeout
            type: input
            className: col-md-6
            defaultValue: 1000
            templateOptions:
              label: Timeout
              description: Timeout in milliseconds for retrieve Subscriber Information from remote system. If timeout reach, system will perform default action.
              type: number
          - key: dry-run
            type: select
            className: col-md-6
            defaultValue: false
            templateOptions:
              label: Dry Run
              description: Turn on Dry Run to let all call pass thru system.
              options:
                - value: false
                  label: Off
                - value: true
                  label: On
          - key: default-code
            type: ng-select
            defaultValue: 1
            className: col-md-6
            expressionProperties:
              templateOptions.disabled: "!model['dry-run']"
            templateOptions:
              label: Dry Run Hangup Cause Code
              description: Default Hangup cause code to use on dry run mode
              multiple: false
              itemEndpoint: /assets/configuration/causecode.json
              key: value
              val: label
      - templateOptions:
          label: MAP Error Mappings
        className: card-body
        fieldGroupClassName: card my-3
        fieldGroup:
          - key: mapHttpErrorMapping
            type: repeat
            className: col-md-12
            templateOptions:
              label: SS7 MAP Error Mapping
              description: Error Mapping between SS7 MAP error code vs internal error code
            fieldArray:
              fieldGroupClassName: row
              fieldGroup:
                - key: errorCode
                  type: ng-select
                  defaultValue: 1
                  className: col-md-4
                  templateOptions:
                    label: MAP Error Code
                    description: Error Code return from HLR
                    multiple: false
                    itemEndpoint: /assets/configuration/map-errors.json
                    key: value
                    val: label
                    groupBy: group
                - key: causeCode
                  type: ng-select
                  defaultValue: 1
                  className: col-md-4
                  templateOptions:
                    label: Error Code
                    description: Error Code to display in CDR, can be used to map against SIP Hangup Cause Code
                    multiple: false
                    itemEndpoint: /assets/configuration/http-codes.json
                    key: value
                    val: label

      - templateOptions:
          label: SIP Cause Codes
        className: card-body
        fieldGroupClassName: card my-3
        fieldGroup:
          - key: errorMap
            type: repeat
            templateOptions:
              label: SIP Error Mapping
              description: Error Mapping between internal Error code vs SIP cause code
            fieldArray:
              fieldGroupClassName: row
              fieldGroup:
                - key: errorCode
                  type: input
                  defaultValue: 1
                  className: col-md-4
                  templateOptions:
                    label: ErrorCode
                    description: Internal Error Code for Mapping
                    type: number
                - key: causeCode
                  type: ng-select
                  defaultValue: 1
                  className: col-md-4
                  templateOptions:
                    label: SIP Cause Code
                    description: Hangup cause code to use
                    multiple: false
                    itemEndpoint: /assets/configuration/causecode.json
                    key: value
                    val: label
                - key: errorDesc
                  type: input
                  className: col-md-4
                  templateOptions:
                    label: Description
                    description: Extra Description to add into CDR
