server:
  port: 8085

# Expose Metrics via Prometheus
management:
  metrics:
    export:
      prometheus:
        enabled: true

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/asterisk
    username: asterisk
    password: asterisk
  cloud:
    consul:
      config:
        watch:
          enabled: true

application:
  callback-url: 'http://localhost:8089/api/public/sms-server/perform-sri-sm'
