# Menu Tree on Top Naviation
- name: Spoofing Hanoi
  url: /docs/README
  authority: ROLE_ADMIN
  children:
    - name: Routing Rules
      url: /data/spoofing-management/routing-rules
      icon: fast-forward
      authority: ROLE_ADMIN
    - name: Whitelist
      url: /data/spoofing-management/whitelist
      icon: shield-alt
      authority: ROLE_ADMIN
    - name: Blacklist
      url: /data/spoofing-management/blacklist
      icon: ban
      authority: ROLE_ADMIN

    - name: CDR Summary
      url: /summary
      icon: chart-pie
      authority: ROLE_ADMIN
    - name: Routes Simulator
      url: /app-management/forms/tools/lookup-route
      icon: directions
      authority: ROLE_ADMIN
    - name: Lookup SRI Info
      url: /app-management/forms/tools/sri
      icon: info-circle
      authority: ROLE_ADMIN
    - name: Call Simulator
      url: /app-management/forms/tools/simulator
      icon: location-arrow
      authority: ROLE_ADMIN
    - name: Tracing
      url: /tracing
      icon: thermometer
      authority: ROLE_ADMIN
    - name: Global Configuration
      url: /app-management/configuration/global-settings
      icon: cogs
      authority: ROLE_ADMIN

- name: Spoofing HCM
  url: /docs/README
  authority: ROLE_ADMIN
  children:
    - name: Routing Rules
      url: /data/spoofing-hcm/routing-rules
      icon: fast-forward
      authority: ROLE_ADMIN
    - name: Whitelist
      url: /data/spoofing-hcm/whitelist
      icon: shield-alt
      authority: ROLE_ADMIN
    - name: Blacklist
      url: /data/spoofing-hcm/blacklist
      icon: ban
      authority: ROLE_ADMIN
    - name: CDR Summary
      url: /summary-hcm
      icon: chart-pie
      authority: ROLE_ADMIN
    - name: Routes Simulator
      url: /app-management/forms/tools/lookup-route-hcm
      icon: directions
      authority: ROLE_ADMIN
    - name: Lookup SRI Info
      url: /app-management/forms/tools/sri-hcm
      icon: info-circle
      authority: ROLE_ADMIN
    - name: Call Simulator
      url: /app-management/forms/tools/simulator-hcm
      icon: location-arrow
      authority: ROLE_ADMIN
    - name: Tracing
      url: /tracing
      icon: thermometer
      authority: ROLE_ADMIN
    - name: Global Configuration
      url: /app-management/configuration/global-settings-hcm
      icon: cogs
      authority: ROLE_ADMIN

- name: Traffic Analyzer
  url: /docs/README
  authority: ROLE_ADMIN
  children:
    - name: Traffic Load Test
      url: '/data/campaign-manager/campaigns'
      icon: clock
    - name: Outbound Calls
      url: '/data/campaign-manager/campaign-calls'
      icon: history
